export const skills = [
  'ActionScript',
  'Ada',
  'ADF',
  'AdMob',
  'Adobe Air',
  'Adobe CQ',
  'AI Engineers',
  'Alfresco',
  'Amazon API',
  'Amazon EC2',
  'Amazon S3',
  'Android',
  'Android SDK',
  'Angular',
  'AngularJS',
  'Ansible',
  'Apache',
  'Apache Click',
  'Apache Cordova',
  'Apache Shale',
  'Apache Struts 2',
  'Apache Tapestry',
  'Apache Wicket',
  'Apex',
  'API',
  'Appcelerator',
  'AppExchange',
  'Apple Watch',
  'ArcGIS',
  'Arch Linux',
  'ARCore',
  'Arduino',
  'ARKit',
  'ARM',
  'ASP.NET',
  'ASP.NET Dynamic Data',
  'ASP.NET MVC',
  'Asterisk',
  'Augmented Reality Developers',
  'Aurelia',
  'Authorize.Net',
  'Automation Developers',
  'AWK',
  'AWS',
  'Azure',
  'Babel',
  'Backbone.js',
  'Back-End Developers',
  'Bash',
  'Big Data Architects',
  'Bing Maps',
  'Bitcoin',
  'Bitcoin Cash',
  'BlackBerry',
  'Blender',
  'Blockchain Developers',
  'Bluetooth',
  'Bootstrap',
  'Bottle',
  'Brew',
  'BuddyPress',
  'Business Intelligence',
  'C',
  'C#',
  'C++',
  'CakePHP',
  'Carma',
  'CartoDB',
  'Cassandra',
  'Catalyst',
  'CherryPy',
  'Chrome Extension Developers',
  'CI/CD Engineers',
  'CiviCRM',
  'Clarion',
  'Clojure',
  'Cloud Engineers',
  'Clover',
  'COBOL',
  'Cocoa',
  'CodeIgniter',
  'CoffeeScript',
  'Cognos',
  'Computer Vision',
  'Core Java',
  'Corona SDK',
  'Cryptocurrency',
  'Crystal Reports',
  'CSLA',
  'CSS',
  'CTOs',
  'CUDA',
  'Cython',
  'D',
  'D3.js',
  'ÐApp',
  'Dart',
  'Data Analysts',
  'Database Developers',
  'Data Engineers',
  'Data Modeling Experts',
  'Data Scientists',
  'Data Warehouse',
  'DB2',
  'Debian',
  'Dedicated Developers',
  'Dedicated Front-End Developers',
  'Dedicated iPhone Developers',
  'Dedicated Java Developers',
  'Dedicated Magento Developers',
  'Dedicated Mobile App Developers',
  'Dedicated .NET Developers',
  'Dedicated PHP Developers',
  'Dedicated Web Developers',
  'Dedicated WordPress Developers',
  'Deep Learning Experts',
  'Demandware',
  'DevExpress',
  'DevOps Engineers',
  'DirectX',
  'Django',
  'Docker',
  'Dojo',
  'Drupal',
  'eBay API',
  'ECMAScript 6',
  'eCommerce',
  'Elasticsearch',
  'Electron',
  'Elixir',
  'Embedded Software Engineers',
  'Ember.js',
  'Erlang',
  'ERP',
  'Ethereum',
  'Ethereum Smart Contract',
  'ETL',
  'Excel',
  'ExpressionEngine',
  'Express.js',
  'Extended Reality Developers',
  'Ext JS',
  'F#',
  'Facebook API',
  'Fat-Free',
  'Financial Software Developers',
  'Firebase',
  'Firefox',
  'Fitbit',
  'Flash',
  'Flask',
  'Flex',
  'Flutter',
  'Force.com',
  'Fortran',
  'FoxPro',
  'FPGA',
  'FreeBSD',
  'Freelance Developers',
  'Friendster',
  'Front-End Developers',
  'FuelPHP',
  'Full-Stack Developers',
  'Game Developers',
  'Gentoo',
  'GIMP',
  'GIS',
  'GitHub',
  'Gmail',
  'Go Engineers',
  'Google AdWords',
  'Google Analytics',
  'Google API',
  'Google App Engine',
  'Google Checkout',
  'Google Docs',
  'Google Drive',
  'Google Glass',
  'Google Latitude',
  'Google Maps',
  'Google Play',
  'Google Sites',
  'Google Storage',
  'Google Web Toolkit',
  'Grails',
  'GraphQL',
  'Grok',
  'Groovy',
  'Hadoop',
  'Haskell',
  'Heroku',
  'HFT',
  'Hibernate',
  'HTC Vive',
  'HTML5',
  'HTML Developers',
  'Hybris',
  'Hyperledger',
  'iAd',
  'iBeacon',
  'iCloud',
  'Informatica',
  'Infusionsoft',
  'Instagram API',
  'Ionic',
  'iOS',
  'iOS Developers',
  'IoT Developers',
  'iPad',
  'iPhone App Development Freelancer',
  'IT',
  'ItsNat',
  'Jade',
  'Java',
  'Java Developers',
  'Java EE',
  'JavaScript',
  'JavaScript Consultants',
  'JBoss',
  'JBoss Seam',
  'Jenkins',
  'JIRA',
  'JMS',
  'jQuery',
  'JSP',
  'Jspx-bay',
  'Julia',
  'JVx',
  'Kafka',
  'Knockout.js',
  'Kohana',
  'Kotlin',
  'LabVIEW',
  'LAMP',
  'Laravel',
  'Layar',
  'Leap Motion',
  'Lift',
  'LinkedIn API',
  'Linux',
  'Lua',
  'Machine Learning Engineers',
  'Magento',
  'Magento Developers',
  'MailChimp',
  'Mason',
  'MATLAB',
  'Maya',
  'MEAN Stack Developers',
  'Meteor',
  'Microsoft Access',
  'Microsoft Dynamics CRM',
  'Microsoft Kinect',
  'Mixed Reality Developers',
  'Mobile App Developers',
  'Mobile Developers',
  'MODx',
  'Mojolicious',
  'MongoDB',
  'Mono',
  'MS SQL Developers',
  'MySQL',
  'Neo4j',
  '.NET',
  'NetBSD',
  'Nette Framework',
  'Neural Network',
  'Nexus',
  'NLP',
  'Node.js',
  'Node.js Developers',
  'nopCommerce',
  'NumPy',
  'Objective-C',
  'OCaml',
  'Octave',
  'Oculus Rift',
  'Offshore Developers',
  'OneDrive',
  'OpenBSD',
  'OpenCart',
  'OpenCV',
  'OpenERP',
  'OpenGL',
  'OpenLaszlo',
  'OpenSocial',
  'OpenStack',
  'Oracle',
  'Oracle ADF',
  'Oracle Forms',
  'Oracle SQL',
  'osCommerce',
  'Outsourced Developers',
  'Padrino',
  'Pandas',
  'Pebble',
  'Perl',
  'Phalcon',
  'Phoenix',
  'PhoneGap',
  'PHP',
  'phpBB',
  'PHP Developers',
  'PHPfox',
  'PHPixie',
  'Play',
  'Plone',
  'PL/SQL',
  'Poco',
  'POS',
  'PostgreSQL',
  'PowerBuilder',
  'PRADO',
  'PrestaShop',
  'Prism',
  'Protractor',
  'Puppeteer',
  'PureMVC',
  'Pyjs',
  'Pylons',
  'PyObjC',
  'PyQt',
  'Pyramid',
  'Python',
  'QA Analysts',
  'QA Engineers',
  'QA Leads',
  'QA Managers',
  'QA Specialists',
  'QA Testers',
  'QlikView',
  'Qt',
  'Quantitative',
  'QuickBase',
  'QuickBooks',
  'R',
  'R3 Corda',
  'Rackspace',
  'Ractive.js',
  'Raspberry Pi',
  'React.js',
  'React Native',
  'Release Engineers',
  'Remote Developers',
  'Ruby',
  'Ruby on Rails',
  'Rust',
  'RxJS',
  'SaaS',
  'Sails.js',
  'Salesforce',
  'Salesforce1',
  'SAS',
  'Sass',
  'Scala',
  'SCM Engineers',
  'SDETs',
  'Selenium',
  'Sencha Touch',
  'SharePoint',
  'Shopify',
  'Silex',
  'Silverlight',
  'SilverStripe',
  'Sinatra',
  'Sitefinity',
  'Smart Contract',
  'Smarty',
  'SOA',
  'Socket.IO',
  'Software Architects',
  'Software Developers',
  'Solaris',
  'Solidity',
  'SOLIDWORKS',
  'Spark',
  'Splunk',
  'Spree Commerce',
  'Spring',
  'Spring Boot',
  'SQL',
  'SQL CLR',
  'SQL Server',
  'Squarespace',
  'SSIS',
  'Stripe',
  'Stripes',
  'Struts',
  'SugarCRM',
  'Swift',
  'Sybase',
  'Symbian',
  'Symfony',
  'Tableau',
  'Technical Writers',
  'Telerik',
  'TensorFlow',
  'Teradata',
  'Test Automation Architects',
  'Test Automation Engineers',
  'Test Engineers',
  'ThinWire',
  'TIBCO',
  'Titanium',
  'Tizen',
  'Tornado',
  'TurboGears',
  'Twilio',
  'Twitter Bootstrap',
  'TypeScript',
  'TYPO3',
  'TYPO3 Flow',
  'Ubuntu',
  'UI',
  'UI, UX, and Front-End Developers',
  'Umbraco',
  'UML',
  'Unified.js',
  'Unity or Unity3D',
  'Unix',
  'Unreal Engine',
  'UX',
  'Vaadin',
  'VBA',
  'VB.NET',
  'vBulletin',
  'Velocity',
  'Vibe.d',
  'Virtual Reality Developers',
  'Visio',
  'Visual Basic',
  'Visualforce',
  'Visual Studio',
  'VMware Engineers',
  'VoIP Engineers',
  'Volusion',
  'VRaptor',
  'vTiger',
  'Vue.js',
  'Vuforia',
  'Wavemaker',
  'web2py',
  'Web Developers',
  'WebKit',
  'WebObjects',
  'webOS',
  'WebRTC',
  'WebSphere',
  'Webware',
  'Weebly',
  'Windows App',
  'Windows Phone',
  'WinForms',
  'WooCommerce',
  'WordPress',
  'WordPress Developers',
  'WordPress Plugin',
  'Wowza',
  'WPF',
  'Xamarin',
  'Xbox',
  'Xcode',
  'Xero',
  'XML',
  'XNA',
  'XP',
  'Yahoo! Store',
  'Yelp API',
  'Yesod',
  'Yii',
  'Yii 2',
  'YouTube API',
  'Zen Cart',
  'Zend',
  'Zendesk',
  'Zope 2',
];
