export const testData = {
  a: 'b',
};

export const getcheer = {
  caption: 'string',
  cheer_type: 'string',
  group: {
    cover: 'string',
    created_at: {
      date: 0,
      day: 0,
      hours: 0,
      minutes: 0,
      month: 0,
      seconds: 0,
      time: 0,
      timezoneOffset: 0,
      year: 0,
    },
    created_by: 'string',
    description: 'string',
    id: 'string',
    image: 'string',
    name: 'string',
    uuid: 'string',
    visibility: true,
  },
  id: 'string',
  image_url: 'string',
  match: {
    date_time: 'string',
    id: 'string',
    is_live: 'string',
    league: {
      id: 'string',
      image: 'string',
      name: 'string',
      season: 'string',
      year: 'string',
    },
    location: 'string',
    match_time: {
      date: 0,
      day: 0,
      hours: 0,
      minutes: 0,
      month: 0,
      seconds: 0,
      time: 0,
      timezoneOffset: 0,
      year: 0,
    },
    stage: {
      id: 'string',
      league_id: 'string',
      name: 'string',
    },
    team_x: {
      club: {
        description: 'string',
        image: 'string',
        name: 'string',
      },
      coach: {
        image: 'string',
        name: 'string',
        overview: ['string'],
      },
      id: 'string',
      name: 'string',
      picture: 'string',
      players: [
        {
          image: 'string',
          name: 'string',
          overview: ['string'],
        },
      ],
    },
    team_x_score: 0,
    team_y: {
      club: {
        description: 'string',
        image: 'string',
        name: 'string',
      },
      coach: {
        image: 'string',
        name: 'string',
        overview: ['string'],
      },
      id: 'string',
      name: 'string',
      picture: 'string',
      players: [
        {
          image: 'string',
          name: 'string',
          overview: ['string'],
        },
      ],
    },
    team_y_score: 0,
  },
  match_time: {
    date: 0,
    day: 0,
    hours: 0,
    minutes: 0,
    month: 0,
    nanos: 0,
    seconds: 0,
    time: 0,
    timezoneOffset: 0,
    year: 0,
  },
  timestamp: {
    date: 0,
    day: 0,
    hours: 0,
    minutes: 0,
    month: 0,
    nanos: 0,
    seconds: 0,
    time: 0,
    timezoneOffset: 0,
    year: 0,
  },
  user: {
    id: 'string',
    profile: {
      badge: 'string',
      cover_photo_url: 'string',
      first_name: 'string',
      id: 'string',
      last_name: 'string',
      profile_photo_url: 'string',
    },
  },
  uuid: 'string',
};
